### ISSUE TITLE
ZMQ error

### ISSUE THREAD

**Issue by powerreactor** [uoguelph-mlrg/Theano-MPI#13]
[load] rank 1 port 5021 zmq error
Traceback (most recent call last):
  File "../lib/base/proc_load_mpi.py", line 122, in <module>
    sock.bind('tcp://*:{0}'.format(config['sock_data']))
  File "zmq/backend/cython/socket.pyx", line 489, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:4824)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7055)
zmq.error.ZMQError: Address already in use

Hi He,

It may be caused by two jobs running on the same node with a same port number. Please try something related to pid to make it unique.

Thanks,

Fei

**Comment by hma02** [comment]
Hi Fei. Changed to use pid and tested 01822c8.

**Comment by powerreactor** [comment]
Hi He,

You cannot just use pid as port number because the port number can only be 0- 65535. Pid can be greater than it.

**Comment by powerreactor** [comment]
[load] rank 0 port 66108 zmq error
Traceback (most recent call last):
  File "../lib/base/proc_load_mpi.py", line 122, in <module>
    sock.bind('tcp://*:{0}'.format(config['sock_data']))
  File "zmq/backend/cython/socket.pyx", line 489, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:4824)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7055)
zmq.error.ZMQError: Permission denied

**Comment by hma02** [comment]
@powerreactor 

I see. Then I need to limit the range of port number. 

Just fixed. See this 29f24dc7

**Comment by powerreactor** [comment]
If you set sock_data to 5001 and pid is 65000, (self.config['sock_data'] + int(pid)) % 65535 will be greater than 65535. You can change it to (self.config['sock_data'] + int(pid)) % 54321

**Comment by hma02** [comment]
Hi Fei @powerreactor ,

Just did a quick test.

```
In [1]: a = 5001+65000

In [2]: a
Out[2]: 70001

In [3]: a%65535
Out[3]: 4466
```

Not sure what do you mean by greater than 65535.
But limiting to 54321 should work as well.

**Comment by powerreactor** [comment]
Sorry, my mistake. You can close this issue. Thanks.
