### ISSUE TITLE
Cifar10_model not found

### ISSUE THREAD

**Issue by benliebersohn** [uoguelph-mlrg/Theano-MPI#24]
I am having trouble executing the included Theano-MPI examples from within a docker container. 
My output is as follows:
`root@503d8c1f182a:/workspace/Theano-MPI/examples# python -u test_easgd.py 
Traceback (most recent call last):
  File "test_easgd.py", line 12, in <module>
    modelclass = 'Cifar10_model') 
  File "/usr/local/lib/python2.7/dist-packages/Theano_MPI-1.0-py2.7.egg/theanompi/rules.py", line 173, in init
    p = subprocess.Popen(command)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`

It appears to not be finding the Cifar10 model, which I can find plainly in theanompi/models/. However even when I run test_easgd.py in the theanompi folder, it gives me the same error. What can I do to restructure the directories such that the test_easgd.py finds the Cifar10 model?

Thank you

**Comment by dlunga** [comment]
@benliebersohn try this:`'''
Example for training on 2 worker GPUs by the rule of EASGD
'''
from theanompi import EASGD

rule=EASGD()

# modelfile: the relative path to the model file
# modelclass: the class name of the model to be imported
rule.init(devices=['cuda0', 'cuda1', 'cuda2'] , # cuda0: server, cuda1 and cuda2: workers
          modelfile = 'theanompi.models.cifar10', 
          modelclass = 'Cifar10_model') 
rule.wait()
`

**Comment by hma02** [comment]
@benliebersohn @dlunga 

The way of finding the model file and model class is a bit of hack right now. See [here](https://github.com/uoguelph-mlrg/Theano-MPI/blob/master/theanompi/worker.py#L179). It requires an absolute path, like something on the `PYTHONPATH`. For example

```bash
modelfile = 'theanompi.models.cifar10'
```

will work because `theanompi` is an absolute python package if installed somewhere. 

To have a customized model discovered by worker.py, you need to put the current working directory in `PYTHONPATH`. That is,

```bash
export PYTHONPATH=$(pwd):$PYTHONPATH
```

will make the current folder available.

Doing it this way allows you to work from a random folder with the following files:

```bash
launch_session.cfg
modelfile.py
```

**Comment by dlunga** [comment]
Thanks that makes it easy.
